name: Check for formatting errors

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  format-check:
    runs-on: ubuntu-latest
    name: "Check All Formatting Rules"
    timeout-minutes: 40
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # Important that this is set so that CI checks are triggered again
          # Without this we would be forever waiting on required checks to pass
          token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}

      # IMPORTANT! This is necessary to make sure that a status is reported on the PR
      # even if the workflow is skipped. If we used GitHub Actions filters, the workflow
      # would not be reported as skipped, but instead would be forever pending.
      #
      # I KNOW THIS SOUNDS CRAZY, BUT IT IS TRUE.
      #
      # Also, it gets worse
      #
      # IMPORTANT! DO NOT CHANGE THE QUOTES AROUND THE GLOBS. THEY ARE REQUIRED.
      # MAKE SURE TO TEST ANY SYNTAX CHANGES BEFORE MERGING.
      - name: Get changed files
        uses: tj-actions/changed-files@v39
        id: changes
        with:
          files_yaml: |
            format:
              - '**/*'
              - '!**/*.md'

      - name: Run airbyte-ci formatting checks
        uses: ./.github/actions/run-dagger-pipeline
        with:
          context: "pull_request"
          subcommand: "format --check"

  notify-failure-slack-channel:
    name: "Notify Slack Channel on Build Failures"
    runs-on: ubuntu-latest
    needs:
      - format-check
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
      - name: Match GitHub User to Slack User
        id: match-github-to-slack-user
        uses: ./.github/actions/match-github-to-slack-user
        env:
          AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format Failure on Master Slack Channel
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          args: >-
            {\"channel\":\"C03BEADRPNY\", \"blocks\":[
            {\"type\":\"divider\"},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Formatting is broken on master! :bangbang: \n\n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}* \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{ steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run> :octavia-shocked: \n\"}},
            {\"type\":\"divider\"}]}
